### ISSUE TITLE
I would like to mention, that the minimum Python version changes form Python 3.6 to Python 3.8.

### ISSUE THREAD

**Issue by stuertz** [conda-forge/python-utils-feedstock#34]
I would like to mention, that the minimum Python version changes form Python 3.6 to Python 3.8.

I just installed an environment, which depends on python-utils, and now I can not execute code anymore. Instead I have to fix to version 3.5.2.

Please fix the minimum Python version. Can the existing versions be build again?

_Originally posted by @spreiter in https://github.com/conda-forge/python-utils-feedstock/issues/31#issuecomment-1657749295_

**Comment by stuertz** [comment]
Regarding rebuild/removal of old version I will try: https://conda-forge.org/docs/maintainer/updating_pkgs.html#maint-fix-broken-packages

**Comment by spreiter** [comment]
Thanks, sounds great!
